version: '3.1'

services:

  php-fpm:
#    build: ./php70
#    build: ./php71
    build: ./php72
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
      - rabbitmq:rabbitmq
    volumes:
      - ../app:/data/www:rw
      - ./php-conf/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php-conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../app:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/data/wwwlogs
    ports:
      - "80:80"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
      build: ./mysql
      ports:
        - "3306:3306"
      volumes:
        - ../data/mysql:/var/lib/mysql:rw
        - ../logs/mysql:/var/lib/mysql-logs:rw
        - ./mysql/conf.d:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: rootroot
        MYSQL_DATABASE: declandragon
        MYSQL_USER: declandragon
        MYSQL_PASSWORD: declandragon
      restart: always
      command: "--character-set-server=utf8"

  redis-db:
      build: ./redis
      command: redis-server --requirepass zhangxuliang
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data
      restart: always

  rabbitmq:
      build: ./rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ../data/rabbitmq/mnesia:/var/lib/rabbitmq/mnesia
      environment:
        RABBITMQ_DEFAULT_USER: declandragon
        RABBITMQ_DEFAULT_PASS: rootroot
      restart: always
      
  mongodb:
      build: ./mongodb
      ports:
        - "27017:27017"
      volumes:
        - ../data/mongodb:/data/db
      environment:
        MONGODB_USERNAME: wl_user
        MONGODB_PASSWORD: rootroot
        MONGODB_DATABASE: declandragon
      restart: always